### ISSUE TITLE
Doesn't work for my iCT220

### ISSUE THREAD

**Issue by aalejandraa2** [Ousret/pyTeliumManager#10]
When trying to do the following:

How to enable computer liaison with Ingenico device
Press "F" button
Press 0 - Telium Manager
Press 5 - Init
Press 1 - Param
Select - Checkout
Select "Enable"
Choose your prefered interface (USB, COM1, COM2)

There is no checkout option. I do have a cash connection option which I enabled. It doesn't give me an option to choose USB though. My M2OS is 47787809. 
Any suggestions?

**Comment by Ousret** [comment]
Hi,

Sorry for the delay, but unless I could see your device, I am not going to be able to help.

What OS are you running ?
What cable are you using ?
What hardware are you using ? iwl ?

**Comment by spiderrabbit** [comment]
> When trying to do the following:
> 
> How to enable computer liaison with Ingenico device
> Press "F" button
> Press 0 - Telium Manager
> Press 5 - Init
> Press 1 - Param
> Select - Checkout
> Select "Enable"
> Choose your prefered interface (USB, COM1, COM2)
> 
> There is no checkout option. I do have a cash connection option which I enabled. It doesn't give me an option to choose USB though. My M2OS is 47787809.
> Any suggestions?

Hi did you ever fix this?
