### ISSUE TITLE
No option to select preferred interface

### ISSUE THREAD

**Issue by spiderrabbit** [Ousret/pyTeliumManager#14]
Thanks for the project
I've got an iWL250. I can open Telium Manager, select 3 for initialization, then 1 for parameters, however I can't see "Checkout", only "Cash Connection"

I can enable this but there is no follow up option to select the preferred interface. 

PC usb A to cradle usb B , PC Ubuntu 18.04 python 2.7

Any ideas?

**Comment by Ousret** [comment]
Hi,

You're welcome. Cash Connection should do it. Everything you describe, I already encountered it. Sometime, there is slight differences between "telium manager" versions.

Just enable "Cash Connection" then do : 
```
ls -l /dev/ttyACM*
```

You should have a `ttyACM0` available.

Then you'll be ready to use it.
Best of lucks.

**Comment by spiderrabbit** [comment]
Yes have done that - getting "Payment terminal isn't ready to accept data from host." using /dev/ttyACM0 (dmesg and lsusb shows cradle connected to PC on ACM0)

There is a USB A on the cradle. Do I need to connect that to the PC serial port, or is there a hidden option within Telium to activate the USB interface for Cash Connection?

**Comment by Ousret** [comment]
So if I understand correctly, your OS show a device listed as `ttyACM0`, but when you try to run this library, you can't even pass the init phase ? 

Few ideas,
  - What is the chmod status on `/dev/ttyACM0`, is your user in the `dialout` group ? Maybe there this is it. `sudo usermod -a -G dialout spiderrabbit`
  - Set the `debug` param to `True` in the library. Past the result if any.

**Comment by spiderrabbit** [comment]
OK permissions on ACM0:
crw-rw---- 1 root dialout 166, 0 Apr  5 19:57 /dev/ttyACM0
groups for user:
$USER dialout sudo

set debugging to true in manager.py
sudo python telium_conn.py
('DEBUG :: try send_signal = ', 'ENQ')
Payment terminal isn't ready to accept data from host. Check if terminal is properly configured or not busy.

**Comment by spiderrabbit** [comment]
M2OS 47788481

**Comment by Ousret** [comment]
I suppose you tried rebooting the device after enabling cash conn. 
I am sorry, after reading your traces, I could not understand why it is not working for you.

If possible, try upgrading your Ingenico device. Be in touch with your reseller.

**Comment by spiderrabbit** [comment]
Someone mentioned using a RS232 to USB A connector working; is this just a straight through cable or does it have a USB->Serial chip inside?
Thanks anyway for the help :)

**Comment by Ousret** [comment]
Should not be possible. Not that I know of. I am closing this issue as it is not a library related incident.
Good luck 👍

**Comment by jnosky** [comment]
I have tried both onboard USB on ICT220 and a USB serial to magic box serial. I verified with an oscilloscope the application is sending serial to the ict220 (magic box), however it does not seem to respond.

I too only have  the "Cash Connection" option. 
Version: 8447788489
I enabled it, rebooted, tried everything. Will not connect.

"Payment terminal isn't ready to accept data from host. Check if terminal is properly configured or not busy"

**Comment by spiderrabbit** [comment]
Apparently "semi-integration" needs to be enabled by the card machine supplier

**Comment by jnosky** [comment]
I called my processor (Elavon) and they said the ICT220  does not support "semi-integration". They said the newer Desk 3500 can be enabled, but only for certain POS software. I assume the semi-integration api is what this project uses. Wondering if anyone has tried with Desk 3500. I had read elsewhere that semi-integration is not available in US.  fwiw the ROM in my ICT220 is nearly full, perhaps why my processor wont support it. I am in US.

**Comment by Ousret** [comment]
Any chances you can get your processor to give you technical sheets (com. protocol) about the "Desk 3550" device ? @jnosky
