### ISSUE TITLE
Create custom request

### ISSUE THREAD

**Issue by freemansgithub** [Ousret/pyTeliumManager#15]
Is it real to create custom request for ict220 ingenicor terminal using your lib? or How should it be extende to do this? We want to change protocol of communication with bank gateway

**Comment by Ousret** [comment]
Hi @freemansgithub 

I made this library for communicating with a micro-software that can be (or not) present in your ingenico device. Here, Telium Manager.
But I don't see why this library can't be used in another context as Telium Manager use the CONCERT + protocol.

I am not sure I have answered your question correctly. Hope this help.
Regards
