### ISSUE TITLE
Working with devices 

### ISSUE THREAD

**Issue by michaelmorar** [Ousret/pyTeliumManager#17]
Greetings, first of all thank you for this library. You have clearly poured a lot of work into this, it looks promising, and there is nothing else like it out there.

I would like to contribute as I am working on a startup in the retail and fine hardware space. 

I have an IWL250 production device. How can I connect it? Do I first need some kind of root access to the Ingenico machine? Is it possible, in your experience, to get test merchant numbers? 

Apologies of these questions are unreasonable or ill informed, I am just trying to get up and running. 

Many thanks 

Michael

**Comment by Ousret** [comment]
Hi @michaelmorar 

You are welcome. Any contribution would be very much appreciated.

> I have an IWL250 production device. How can I connect it?

You'll need to plug a USB type A to B (90° angle) into the iWL250 and follow the steps (see README.md) on your terminal to enable the "Cash conn."  through USB.

> Do I first need some kind of root access to the Ingenico machine?
> Is it possible, in your experience, to get test merchant numbers?

In my experiences, I have always used bank services to retrieve those devices.

(i) You absolutely should not try anything that was not meant for the end-user. It's illegal and will very much likely be reported to your vendor through their web service. (Checksum and whatnot)
(ii) I am not sure what you meant by "test merchant numbers?".

**Comment by michaelmorar** [comment]
Hi @Ousret  -thank you for replying so quickly!

By my last question, I think I was asking how to get a non-production (not meant for end users) device that I could use to work with your software.

It sounds like I need to approach an acquiring bank. In the UK market, there are several but I don't have any partners or contacts in those institutions so it is time for me to some legwork. 

Many thanks again!

Michael

**Comment by Ousret** [comment]
Hi @michaelmorar 

>  I think I was asking how to get a non-production (not meant for end users) device
The only way you could do that is to make your bank (provider/reseller) believe you need to allow your tech (pos vendor) to remotely enable debug. Then, if your vendor/provider is nice enough, it will proceed remotely. The debug mode is not as open as you could think unfortunately. So don't get your hope too high.

> It sounds like I need to approach an acquiring bank.
Yes pretty much the case.

You are welcome.
Best of luck.
