### ISSUE TITLE
Unable to open ingenico ict220 liason Checkout not found

### ISSUE THREAD

**Issue by c-amara** [Ousret/pyTeliumManager#19]
Hello, I'm trying to enable ingenico liason but the "checkout" is not available under menu you listed in "How to enable computer liaison with Ingenico device". 
And the connection does not work.
Have you a solution?

**Comment by Ousret** [comment]
Hi,

Unfornutaly if this option is missing, this is likely that your device is either "limited" or missing a micro-software inside.
You'll have to refer to a bank.

**Comment by c-amara** [comment]
Hi, I already asked to bank and they suggest me to activate the "liason" (Amount exchange) over ethernet beacuse they told me that no one of their customer use this method (over USB/COM cable).

**Comment by Ousret** [comment]
Hi,

I am not aware of the protocol over ethernet. I wish I have. Could you try to obtain a copy by soliciting your bank? You may have to be quite insisting. If you obtain such a copy, please forward it to me by email.

Regards,
