### ISSUE TITLE
Add support for iPP3XX devices

### ISSUE THREAD

**Issue by Ousret** [Ousret/pyTeliumManager#2]
Support for iPP3XX mobile payment device
-------------------------------------------

*To be clear, all iWL 2XX are currently supported and will still be supported there on next release.*

Next stage for pyTeliumManager is to support next gen mobile payment device.
I'm targeting iPP 3XX devices.

- [x] Buy iPP3XX standalone mobile payment device.
- [x] Enable USB conn. on device.
- [x] Search for dev docs or trying reverse engineering.
- [ ] Adapt TeliumData classes.
- [ ] Create submodule TCP/IP proxy through usb serial. (AT Command)
- [ ] Tests

**Comment by Ousret** [comment]
As I thought..

```sh
my_device.ask(my_payment)
> DEBUG wait_signal_received =  ACK
> DEBUG wait_signal_received =  NAK
> False
```

As expected 3XX devices aren't supported. This happen because encoded data from TeliumAsk aren't recognised by device.

**Comment by evgenmedia** [comment]
Hello!

Where did you find docs for Telium?

We planed to developer vending machine, and we want to integrate ingenico terminals with our software, bug can't find any SDK to communicate with terminal via TCP/IP(

**Comment by Ousret** [comment]
Hi,

There was some reverse engineering and I accidentally found a part of the documentation online three years ago. I also tried to ask nicely Ingenico in France, In short terms, I had no nice answer. This package is a combination of perseverance, luck and clues.

If you want to find a way to communicate with a Ingenico device with TCP/IP as mode of sending order you may end up asking a random market to explore his setup and ultimately listen TCP/IP conn.

Hope you succeed.

**Comment by orestis-z** [comment]
@evgenmedia @Ousret are you familiar with any POS terminal providers that offer an SDK to control their devices without having to contact their sales department?
