### ISSUE TITLE
"Payment terminal isn't ready to accept data from host."

### ISSUE THREAD

**Issue by jess-sys** [Ousret/pyTeliumManager#5]
Got this error each time I try to run the example code:

> Payment terminal isn't ready to accept data from host. Check if terminal is properly configured or not busy.

I checked /dev/ttyACM0. I enabled "Cash connection" on Telium Manager.

Device: Ingenico iCT250 using standard USB cable.

**Comment by PeterAlabaster** [comment]
How are you connecting the device to the pc? I found when I used the dedicated USB B --> A connector directly on the terminal itself, I could not form any soft of connection with the device.

However, when using a Serial --> USB A connector (out of the 'magic box') I could form a connection.
