### ISSUE TITLE
Connecting a terminal wirelessly to my computer

### ISSUE THREAD

**Issue by vkozin97** [Ousret/pyTeliumManager#8]
I have an Ingenico IWL250 terminal, but I have no base for it. The base is a big box onto which the terminal is being put, and, as I understood, which is intended to be a connector between the terminal and the computer. I, not having such a base, wonder if it is possible to connect my terminal to computer wirelessly, via WiFi maybe, or in any other way. Googling this haven't made any results, so I'd be grateful if somebody here has already faced problems like that and can share some useful pieces of advice.

**Comment by Ousret** [comment]
Hi,

There's actually no way to send command wirelessly to your terminal in your actual state. 
Maybe thought a  pluggable BT adapter, never looked into for the moment being. Try to buy a BT card compatible with iWL250 and observe if telium manager recognizes your card. If so, I could upgrade this lib to make it work.

🤝
