### ISSUE TITLE
A non-intrusive way to check everything is OK

### ISSUE THREAD

**Issue by azmeuk** [Ousret/pyTeliumManager#9]
Hi.
First of all, thank you for your work.

In the documentation I did not see nothing about checking the terminal status. I would love such a feature. Ideally a `Telium.is_ok()` returning a boolean wether the terminal is ready or not (something may has happened with the software, the terminal wire may have been disconnected etc.)

What do you think?

**Comment by Ousret** [comment]
Hi,

You are welcome. I remember trying to implement something like `Telium.is_ok()` but for some reason this could lead to bugs. I was trying to send ACK .. waiting for answer .. then send NAK. When I tested it in real condition I noticed that some transaction randomly ended up with NAK. Maybe it was isolated.

Do you think you could propose a PR and test it locally ?

Thank.

**Comment by Ousret** [comment]
Should be fixed by #12

**Comment by azmeuk** [comment]
Thank you!
